#!/bin/bash

SPATH=$(dirname $(realpath $0))

mkdir -p ~/bin
ln -s $SPATH/mpv ~/bin/

# if default config not exist
[ ! -f ~/.config/mpv/input.conf.1 ] \
    && cp /usr/share/examples/mpv/input.conf  ~/.config/mpv/input.conf.1
